springdoc.api-docs.path=/api-docs
server.servlet.contextPath=/score/v3
server.port=8080
spring.jackson.date-format=io.poleray.RFC3339DateFormat
spring.jackson.serialization.WRITE_DATES_AS_TIMESTAMPS=false
spring.data.mongodb.uri=mongodb://localhost:27017

# Per-app API tokens (app.tokens.{appName}=secret)
# Example:
# app.tokens.Sigma-5=neidn475$##@[wkdkm
# app.tokens.wordrix=moeo_hruywk3844-#044d
